import requests
from bs4 import BeautifulSoup
import os
import time
import sqlite3
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv

load_dotenv()

DB_PATH = os.getenv("DB_PATH", "/app/data")
DB_NAME = os.path.join(DB_PATH, "products.db")
LOGIN_URL = os.getenv("TARGET_LOGIN_URL")
BASE_URL = os.getenv("TARGET_BASE_URL")
DOMAIN = os.getenv("TARGET_DOMAIN")

def send_email(subject, body_html):
    sender = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    receiver = os.getenv("EMAIL_RECEIVER")
    
    msg = MIMEMultipart()
    msg['From'] = f"Price Monitor <{sender}>"
    msg['To'] = receiver
    msg['Subject'] = subject
    msg.attach(MIMEText(body_html, 'html'))

    try:
        with smtplib.SMTP(os.getenv("SMTP_SERVER"), int(os.getenv("SMTP_PORT"))) as server:
            server.starttls()
            server.login(sender, password)
            server.send_message(msg)
        print("📧 Email sent successfully.")
    except Exception as e:
        print(f"❌ Email error: {e}")

def generate_report(changes):
    if not changes:
        return "<p style='font-family: Arial;'>No changes detected.</p>"
    
    rows = ""
    for change in changes:
        colors = {
            "PRICE_DROP": "#d9534f",
            "NEW_PRODUCT": "#5cb85c",
            "RESTOCKED": "#5bc0de",
            "OUT_OF_STOCK": "#777",
            "PRICE_CHANGE": "#f0ad4e"
        }
        color = colors.get(change["type"], "#333")
        
        rows += f"""
        <tr>
            <td style='border:1px solid #ddd; padding:15px; font-family: Arial, sans-serif;'>
                <span style='color:{color}; font-weight:bold; font-size: 13px;'>[{change["type"]}]</span><br>
                <a href='{change["url"]}' style='color: #007bff; text-decoration: none; font-size: 17px; font-weight: bold;'>
                    {change["name"]}
                </a><br>
                <span style='color: #444; font-size: 14px;'>{change["message"]}</span>
            </td>
        </tr>
        """
    
    return f"""
    <h2 style='font-family: Arial;'>Daily Price Monitor Report</h2>
    <table style='border-collapse: collapse; width: 100%; max-width: 600px;'>
        {rows}
    </table>
    <p style='font-family: Arial; font-size: 12px; color: #888;'>Generated by automated monitor.</p>
    """

def initialize_database():
    if not os.path.exists(DB_PATH):
        os.makedirs(DB_PATH)
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS products (
            sku TEXT PRIMARY KEY,
            name TEXT,
            max_price TEXT,
            min_price TEXT,
            in_stock INTEGER DEFAULT 1,
            last_seen DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    conn.commit()
    return conn

def fetch_product_data(session, url):
    try:
        response = session.get(url, timeout=10)
        soup = BeautifulSoup(response.content, 'html.parser')
        sku = soup.find('span', {'itemprop': 'sku'})
        
        max_price_tag = soup.find('meta', {'itemprop': 'maxPrice'})
        min_price_tag = soup.find('meta', {'itemprop': 'minPrice'})
        old_price_tag = soup.find('span', class_='old-price') or soup.find('del')
        
        if not max_price_tag:
            max_price_tag = soup.find('meta', {'itemprop': 'price'})
        if not min_price_tag:
            min_price_tag = soup.find('meta', {'itemprop': 'price'})

        max_price = max_price_tag['content'] if max_price_tag else "0"
        min_price = min_price_tag['content'] if min_price_tag else "0"
        original_price = old_price_tag.text.strip() if old_price_tag else None
        
        error_msg = soup.find('div', class_=lambda c: c and 'errormessage' in c)
        in_stock = 0 if error_msg else 1

        if sku:
            return {
                'sku': sku.text.strip(),
                'name': soup.find('h1').text.strip() if soup.find('h1') else "Unknown",
                'max_price': max_price,
                'min_price': min_price,
                'original_price': original_price,
                'in_stock': in_stock
            }
    except Exception as e:
        print(f"⚠️ Error fetching {url}: {e}")
    return None

def crawl_and_process(session, url, conn, visited, changes):
    if url in visited:
        return
    visited.add(url)
    print(f"🔍 Processing: {url}")
    cursor = conn.cursor()
    
    try:
        response = session.get(url, timeout=15)
        soup = BeautifulSoup(response.content, 'html.parser')

        for link in soup.find_all('a', href=True):
            href = link['href']
            if "action=" in href:
                continue
            if ("/Produkte/" in href or "/Products/" in href) and ":::" in href:
                clean_path = href.replace(DOMAIN, "").lstrip('/')
                crawl_and_process(session, DOMAIN + clean_path, conn, visited, changes)

        product_links = set()
        for link in soup.find_all('a', href=True):
            href = link['href']
            if "action=" in href:
                continue
            if ("/Produkte/" in href or "/Products/" in href) and ":::" not in href.split("/")[-1]:
                clean_path = href.replace(DOMAIN, "").lstrip('/')
                product_links.add(DOMAIN + clean_path)

        for product_url in product_links:
            data = fetch_product_data(session, product_url)
            if not data:
                continue

            cursor.execute("SELECT max_price, min_price, in_stock FROM products WHERE sku=?", (data['sku'],))
            old_record = cursor.fetchone()

            if old_record is None:
                changes.append({
                    "type": "NEW_PRODUCT", 
                    "name": f"{data['sku']} - {data['name']}", 
                    "url": product_url, 
                    "message": f"Max: {data['max_price']} | Min: {data['min_price']} (Stock: {'Yes' if data['in_stock'] else 'No'})"
                })
                cursor.execute("INSERT INTO products (sku, name, max_price, min_price, in_stock) VALUES (?,?,?,?,?)",
                             (data['sku'], data['name'], data['max_price'], data['min_price'], data['in_stock']))
            else:
                old_max, old_min, old_stock = old_record
                
                if (old_max != data['max_price'] or old_min != data['min_price']) and old_max != "0":
                    change_type = "PRICE_DROP" if data['original_price'] else "PRICE_CHANGE"
                    original_info = f" (originally {data['original_price']})" if data['original_price'] else ""
                    
                    changes.append({
                        "type": change_type, 
                        "name": f"{data['sku']} - {data['name']}", 
                        "url": product_url,
                        "message": f"Max: {old_max} -> {data['max_price']} | Min: {old_min} -> {data['min_price']}{original_info}"
                    })

                if old_stock != data['in_stock']:
                    stock_type = "RESTOCKED" if data['in_stock'] == 1 else "OUT_OF_STOCK"
                    stock_msg = "Back in stock!" if data['in_stock'] == 1 else "Out of stock."
                    changes.append({"type": stock_type, "name": data['name'], "url": product_url, "message": stock_msg})

                cursor.execute("UPDATE products SET max_price=?, min_price=?, in_stock=?, last_seen=CURRENT_TIMESTAMP WHERE sku=?",
                             (data['max_price'], data['min_price'], data['in_stock'], data['sku']))
            
            conn.commit()
            time.sleep(0.2)

    except Exception as e:
        print(f"❌ Crawl error: {e}")

def run_monitor():
    conn = initialize_database()
    username = os.getenv("TARGET_USERNAME")
    password = os.getenv("TARGET_PASSWORD")
    visited, changes = set(), []

    with requests.Session() as session:
        session.headers.update({'User-Agent': 'Mozilla/5.0'})
        print("🔑 Authenticating...")
        session.post(LOGIN_URL, data={'email_address': username, 'password': password})
        crawl_and_process(session, BASE_URL, conn, visited, changes)

    report_html = generate_report(changes)
    send_email(f"Monitor Report: {len(changes)} changes detected", report_html)
    conn.close()

if __name__ == "__main__":
    run_monitor()
